import { createSlice, createSelector } from '@reduxjs/toolkit';
import books from './booksData';

//Initial state containing the list of books
const initialState = {
    books,
  };
  
  //Creating a slice for books with no reducers (as we're just creating selectors here)
  const booksSlice = createSlice({
    name: 'books',  //Name of the slice
    initialState,  //Initial state of the slice
    reducers: {},  //No reducers defined here
  });
  
  //Selector to get all books from the state
  export const selectBooks = state => state.books.books;
  
  //Selector to get only the horror books from the state
  export const selectHorrorBooks = createSelector(
    [selectBooks],  //Input selector: getting all books
    books => books.filter(book => book.genre === 'Horror')  //Output selector: filtering books by 'Horror' genre
  );
  
  //Selector to get only the fantasy books from the state
  export const selectFantasyBooks = createSelector(
    [selectBooks],  //Input selector: getting all books
    books => books.filter(book => book.genre === 'Fantasy')  //Output selector: filtering books by 'Fantasy' genre
  );
  
  //Selector to get only the science fiction books from the state
  export const selectScienceFictionBooks = createSelector(
    [selectBooks],  //Input selector: getting all books
    books => books.filter(book => book.genre === 'Science Fiction')  //Output selector: filtering books by 'Science Fiction' genre
  );
  
  //Exporting the reducer generated by the slice
  export default booksSlice.reducer;